name: build
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y nasm build-essential cmake
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build -j
      - name: Smoke test
        run: |
          ./build/hydro examples/return_ok.hy
          ./out || true
          echo "exit code: $?"
